server:
  servlet:
    context-path: /book-market/api
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book-market
    username: postgres
    password:

  rabbitmq:
    port: 5672
    host: localhost

queue-name: user_order_queue
